name: AndroidBuild

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: "18"
          distribution: "temurin"

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew  # Adds executable permission to gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3

        with:
          name: MovieApp.apk
          ppath: app/build/outputs/apk/debug/app-debug.apk